apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch.default.svc.cluster.local:9200"]
    elasticsearch.ssl.verificationMode: none
    xpack.security.enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.12.0
          
          env:                      # <-- ADD THIS BLOCK
            - name: KIBANA_PATH_CONF
              value: /usr/share/kibana/config

          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
 
 
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30061
  selector:
    app: kibana
