stages:
  gen_params:
    deps:
      - MLOpsPipeline/data/data_slices
      - MLOpsPipeline/codes/generate_params.py
    cmd: python3 MLOpsPipeline/codes/generate_params.py
    outs:
      - params.yaml

  train:
    deps:
      - MLOpsPipeline/data/data_slices
      - MLOpsPipeline/codes/train.py
      - MLOpsPipeline/codes/pipeline.py
      - MLOpsPipeline/codes/data_loader.py
      - params.yaml
    outs:
      - MLOpsPipeline/models/model.pkl
    cmd: "python3 MLOpsPipeline/codes/train.py \
        --slice $(yq -r '.train.slice' params.yaml) \
        --output $(yq -r '.train.output' params.yaml)"


