apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambulance-service
  namespace: spe-system-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambulance-service
  template:
    metadata:
      labels:
        app: ambulance-service
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
        - name: ambulance-service
          image: ambulance-location-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
