apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-service
  namespace: spe-system-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emergency-service
  template:
    metadata:
      labels:
        app: emergency-service
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
        - name: emergency-service
          image: emergency-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
