apiVersion: v1
kind: Service
metadata:
  name: emergency-service
  namespace: spe-system-1
spec:
  type: NodePort
  selector:
    app: emergency-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30093
